# Generated by Django 5.2.3 on 2025-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemCondition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
