# Generated by Django 5.2.3 on 2025-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isInMarketPlaces',
            field=models.BooleanField(null=True),
        ),
    ]
