# Generated by Django 5.2.3 on 2025-07-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0002_item_isinmarketplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
    ]
