# Generated by Django 5.2.3 on 2025-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0002_item_created_at_item_user_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
