# Generated by Django 5.2.3 on 2025-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0003_remove_item_created_at_remove_item_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='exp_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
